# Generated by Django 4.1 on 2023-06-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField()),
                ('title_order', models.CharField(max_length=255)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('final_cost', models.IntegerField(blank=True, default=0)),
                ('payment_status', models.CharField(default='Не оплачено', max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('assingned_crew', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assingned_crew', to='users.crew')),
                ('building_address', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='building_address', to='users.address')),
                ('construction_type', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='construction_type', to='crm.constructiontype')),
                ('special_work', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='special_work', to='crm.specialwork')),
                ('state_order', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='state_order', to='crm.statetype')),
            ],
        ),
        migrations.CreateModel(
            name='ImageDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_img', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='crm.currentreport')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_path', models.CharField(blank=True, max_length=255)),
                ('official_company', models.BooleanField(blank=True, default=True)),
                ('name_company', models.CharField(max_length=255)),
                ('person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('loyalty', models.CharField(max_length=10)),
                ('add_info', models.TextField()),
                ('country', models.CharField(default=None, max_length=255)),
                ('region', models.CharField(default=None, max_length=255)),
                ('city', models.CharField(blank=True, default=None, max_length=255)),
                ('street', models.CharField(blank=True, default=None, max_length=255)),
                ('house', models.CharField(blank=True, default=None, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True)),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='users.address')),
            ],
        ),
    ]
