# Generated by Django 4.1 on 2023-06-17 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('crm', '0003_remove_clientcompany_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedb',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='crm.currentreport'),
        ),
        migrations.AlterField(
            model_name='order',
            name='assingned_crew',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assingned_crew', to='users.crew'),
        ),
        migrations.AlterField(
            model_name='order',
            name='building_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_address', to='users.address'),
        ),
    ]
