# Generated by Django 4.2 on 2023-05-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dismissal_at',
        ),
    ]
