# Generated by Django 4.2 on 2023-05-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_groups_alter_customuser_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='positions',
            field=models.ManyToManyField(related_name='user_positions', to='users.position'),
        ),
    ]
