# Generated by Django 4.2 on 2023-05-03 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_skill', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='description',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='position',
            name='skills_required',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='title',
        ),
        migrations.AddField(
            model_name='skill',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='skill_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='skill_type', to='users.typeskill'),
        ),
    ]
