# Generated by Django 4.2 on 2023-05-03 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_typeskill_rename_description_skill_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_position', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_salary', models.IntegerField()),
                ('requirements', models.TextField(default=None)),
                ('responsibilities', models.TextField(default=None)),
                ('experience_required', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_state', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='states',
        ),
        migrations.RemoveField(
            model_name='position',
            name='base_salary',
        ),
        migrations.RemoveField(
            model_name='position',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
        migrations.RemoveField(
            model_name='position',
            name='experience_required',
        ),
        migrations.RemoveField(
            model_name='position',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='position',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='position',
            name='title',
        ),
        migrations.RemoveField(
            model_name='state',
            name='title',
        ),
        migrations.AddField(
            model_name='position',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='position_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='state',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='state_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='position',
            name='type_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_type', to='users.typeposition'),
        ),
        migrations.AddField(
            model_name='state',
            name='type_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_type', to='users.typestate'),
        ),
    ]
